name: Build MariaDB on macOS

on:
  push:
    branches:
      - 11.6
  pull_request:
    branches:
      - 11.6

env:
  MARIADB_VERSION: 11.6

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install cmake openssl ncurses readline jemalloc curl

    - name: Configure MariaDB
      run: |
        mkdir outputdir
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=system -DWITH_JEMALLOC=ON

    - name: Build MariaDB
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)

    - name: Package MariaDB as tar.gz
      run: |
        cd build
        make outputdir

    - name: Create outputdir directory
      run: |
        mkdir -p outputdir/usr/local/mariadb

    - name: Extract tar.gz to outputdir directory
      run: |
        tar -xzvf build/*.tar.gz --strip-components=1 -C outputdir/usr/local/mariadb/

    - name: Create installer outputdir
      run: |
        pkgbuild --root outputdir --identifier com.example.mariadb --version ${{ env.MARIADB_VERSION }} --install-location /usr/local mariadb-${{ env.MARIADB_VERSION }}.pkg

    - name: Upload installer outputdir
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-installer-outputdir
        path: mariadb-${{ env.MARIADB_VERSION }}.pkg