name: Build MariaDB on Ubuntu 22.04

on:
  push:
    branches:
      - 11.6
  pull_request:
    branches:
      - 11.6

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential libssl-dev libncurses5-dev libreadline-dev libaio-dev libjemalloc-dev libcurl4-openssl-dev libldap2-dev libmariadb-dev-compat libmariadb-dev

    - name: Configure MariaDB
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build MariaDB
      run: |
        cd build
        make -j$(nproc)

    - name: Package MariaDB as tar.gz
      run: |
        cd build
        make package

    - name: Create DEB package
      run: |
        mkdir -p build/deb/DEBIAN
        mkdir -p build/deb/usr/local/mariadb
        # Copy the necessary files to the DEB package directory
        find build -maxdepth 1 -type f -exec cp {} build/deb/usr/local/mariadb/ \;
        find build -maxdepth 1 -type d -not -name 'deb' -exec cp -r {} build/deb/usr/local/mariadb/ \;
        # Create the control file
        echo "Package: mariadb" > build/deb/DEBIAN/control
        echo "Version: 11.6" >> build/deb/DEBIAN/control
        echo "Section: base" >> build/deb/DEBIAN/control
        echo "Priority: optional" >> build/deb/DEBIAN/control
        echo "Architecture: amd64" >> build/deb/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> build/deb/DEBIAN/control
        echo "Description: MariaDB database server" >> build/deb/DEBIAN/control
        # Build the DEB package
        dpkg-deb --build build/deb build/mariadb-11.6.deb

    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-binary-package
        path: build/*.deb
