name: Build MariaDB 11.6 on Windows

on:
  push:
    branches:
      - 11.6
  pull_request:
    branches:
      - 11.6

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install ninja
        choco install strawberryperl
        choco install visualstudio2019-workload-vctools
        choco install gnutls --pre

    - name: Download and install Bison
      run: |
        Invoke-WebRequest -Uri "http://gnuwin32.sourceforge.net/downlinks/bison-bin-zip.php" -OutFile bison.zip
        Expand-Archive -Path bison.zip -DestinationPath C:\GnuWin32
        $env:PATH += ";C:\GnuWin32\bin"
        echo "BISON_EXECUTABLE=C:/GnuWin32/bin/bison.exe" >> $GITHUB_ENV
        
    - name: Set environment variables for GnuTLS
      run: |
        echo "GNUTLS_LIBRARY=C:\ProgramData\chocolatey\lib\gnutls\tools\gnutls-cli-debug\lib\libgnutls.lib" >> $GITHUB_ENV
        echo "GNUTLS_INCLUDE_DIR=C:\ProgramData\chocolatey\lib\gnutls\tools\gnutls-cli-debug\include" >> $GITHUB_ENV
        
    - name: Create build directory
      run: |
        if (-Not (Test-Path -Path "build")) {
          mkdir build
        }

    - name: Configure MariaDB
      run: |
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITH_UNIT_TESTS=OFF

    - name: Build MariaDB
      run: |
        cd build
        ninja

    - name: Package MariaDB
      run: |
        cd build
        cpack -G WIX

    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-binary-package
        path: build/*.msi
