name: Build MariaDB 11.6 on Windows

on:
  push:
    branches:
      - 11.6
  pull_request:
    branches:
      - 11.6

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install dependencies
      run: |
        choco install diffutils -y
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install ninja -y
        choco install strawberryperl -y
        choco install visualstudio2019-workload-vctools -y

    - name: Create build directory
      run: |
        if (-Not (Test-Path -Path "build")) {
          mkdir build
        }

    - name: Configure MariaDB
      run: |
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITH_UNIT_TESTS=OFF

    - name: Build MariaDB
      run: |
        cd build
        ninja

    - name: Package MariaDB
      run: |
        cd build
        cpack -G WIX

    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-binary-package
        path: build/*.msi
