name: Build MariaDB 11.6 on Windows

on:
  push:
    branches:
      - '11.6'
  pull_request:
    branches:
      - '11.6'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          base-devel
          mingw-w64-x86_64-toolchain
          bison
          diffutils
          cmake
          ninja

    - name: Add MSYS2 to PATH
      run: |
        echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH

    - name: Verify Bison installation
      shell: msys2
      run: bison --version
    
    - name: Install dependencies
      run: |
        choco install visualstudio2019-workload-vctools -y

    - name: Create build directory
      run: |
        if (-Not (Test-Path -Path "build")) {
          mkdir build
        }

    - name: Configure MariaDB
      run: |
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITH_UNIT_TESTS=OFF

    - name: Build MariaDB
      run: |
        cd build
        ninja

    - name: Package MariaDB
      run: |
        cd build
        cpack -G WIX

    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-binary-package
        path: build/*.msi
