name: Build MariaDB 11.6 on Windows

on:
  push:
    branches:
      - '11.6'
  pull_request:
    branches:
      - '11.6'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          base-devel
          mingw-w64-x86_64-toolchain
          bison
          diffutils
          cmake
          ninja
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-libevent
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-lzo2
          mingw-w64-x86_64-snappy

    - name: Add MSYS2 to PATH
      run: |
        echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH

    - name: Verify Bison installation
      shell: msys2 {0}
      run: bison --version
    
    - name: Install Judy library
      shell: msys2 {0}
      run: |
        pacman -S --noconfirm git wget tar
        wget https://sourceforge.net/projects/judy/files/judy/Judy-1.0.5/Judy-1.0.5.tar.gz
        tar -xzf Judy-1.0.5.tar.gz
        cd Judy-1.0.5
        ./configure --prefix=/mingw64
        make
        make install

    - name: Install dependencies
      run: |
        choco install visualstudio2019-workload-vctools -y

    - name: Create build directory
      run: |
        if (-Not (Test-Path -Path "build")) {
          mkdir build
        }

    - name: Configure MariaDB
      shell: msys2 {0}
      run: |
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITH_UNIT_TESTS=OFF -DWITH_OQGRAPH=OFF

    - name: Build MariaDB
      shell: msys2 {0}
      run: |
        cd build
        ninja

    - name: Package MariaDB
      shell: msys2 {0}
      run: |
        cd build
        cpack -G WIX


    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-binary-package
        path: build/*.msi
